[package]
name = "spectroscopy-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "^0.1"
thiserror = "^2"

tokio = { version = "^1", features = ["sync", "rt-multi-thread"], default-features = false }

spectroscopy-core = { path = "../spectroscopy-core" }
