[package]
name = "nitinol-projection"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
thiserror = "^2"

tracing = { version = "^0.1" }

nitinol-core = { path = "../nitinol-core" }
nitinol-protocol = { path = "../nitinol-protocol" }