[package]
name = "spectroscopy"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ReiRokusanami <reirokusanami.rdh@gmail.com>"]
repository = "https://github.com/HalsekiRaika/spectroscopy"
description = "A event projector(materializer) for event sourcing"

[dependencies]
thiserror = "^2"
async-trait = "^0.1"
serde = "^1"
futures = { version = "^0.3", features = [] }
tracing = "^0.1"
tokio = { version = "^1", features = ["sync", "rt-multi-thread"], default-features = false }

[dev-dependencies]
tokio = { version = "^1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"