[workspace]
members = [
  ".",
  "nitinol-core",
  "nitinol-process",
  "nitinol-protocol",
  "nitinol-projection",
  "nitinol-persistence",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ReiRokusanami <reirokusanami.rdh@gmail.com>"]
repository = "https://github.com/HalsekiRaika/nitinol"
description = "A utilities for event sourcing"

[features]
process = []
sqlite = ["protocol", "nitinol-protocol/sqlite"]
inmemory = ["protocol", "nitinol-protocol/inmemory"]
protocol = []
projection = []

[package]
name = "nitinol"
version = "0.2.0-alpha"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ReiRokusanami <reirokusanami.rdh@gmail.com>"]
repository = "https://github.com/HalsekiRaika/nitinol"
description = "A utilities for event sourcing"

[dependencies]
nitinol-core = { path = "nitinol-core" }
nitinol-protocol = { path = "nitinol-protocol" }
nitinol-process = { path = "nitinol-process" }
nitinol-projection = { path = "nitinol-projection" }


[dev-dependencies]
