[package]
name = "spectrum"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "^1"
async-trait = "^0.1"
serde = "^1"
futures = { version = "^0.3", features = [] }

[dev-dependencies]
tokio = { version = "^1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"