[workspace]
members = [
  ".",
  "nitinol-core",
  "nitinol-executor",
  "nitinol-macro",
  "nitinol-process",
  "nitinol-protocol",
  "nitinol-projection",
  "nitinol-persistence",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ReiRokusanami <reirokusanami.rdh@gmail.com>"]
repository = "https://github.com/HalsekiRaika/nitinol"
description = "A utilities for event sourcing"

[features]
macro = []
process = []
process-ext = ["process"]
persistence = ["process", "process-ext", "protocol"]
sqlite = ["protocol", "nitinol-protocol/sqlite"]
inmemory = ["protocol", "nitinol-protocol/inmemory"]
protocol = []
projection = []

[package]
name = "nitinol"
version = "0.2.0-alpha"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ReiRokusanami <reirokusanami.rdh@gmail.com>"]
repository = "https://github.com/HalsekiRaika/nitinol"
description = "A utilities for event sourcing"

[dependencies]
nitinol-core = { path = "nitinol-core" }
nitinol-macro = { path = "nitinol-macro" }
nitinol-protocol = { path = "nitinol-protocol" }
nitinol-process = { path = "nitinol-process" }
nitinol-projection = { path = "nitinol-projection" }
nitinol-persistence = { path = "nitinol-persistence" }


[dev-dependencies]
nitinol = { path = ".", features = ["macro", "process", "persistence", "projection", "inmemory"] }

async-trait = "^0.1"

serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
anyhow = "^1"
thiserror = "^2"

tokio = { version = "^1", features = ["macros", "rt-multi-thread"] }