[workspace]
members = [
  ".",
  "spectroscopy-core",
  "spectroscopy-protocol",
  "spectroscopy-agent",
  "spectroscopy-projection",
]

resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ReiRokusanami <reirokusanami.rdh@gmail.com>"]
repository = "https://github.com/HalsekiRaika/spectroscopy"
description = "A utilities for event sourcing"

[features]
agent = []
sqlite = ["protocol", "spectroscopy-protocol/sqlite"]
inmemory = ["protocol", "spectroscopy-protocol/inmemory"]
protocol = []
projection = []

[package]
name = "spectroscopy"
version = "0.2.0-alpha"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ReiRokusanami <reirokusanami.rdh@gmail.com>"]
repository = "https://github.com/HalsekiRaika/spectroscopy"
description = "A utilities for event sourcing"

[dependencies]
spectroscopy-core = { path = "spectroscopy-core" }
spectroscopy-protocol = { path = "spectroscopy-protocol" }
spectroscopy-agent = { path = "spectroscopy-agent" }
spectroscopy-projection = { path = "spectroscopy-projection" }


[dev-dependencies]
