[package]
name = "saga-basic-saga"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Minimal event-sourced process manager (Saga) example"

[lib]
name = "saga_basic_saga"
path = "src/lib.rs"

[[bin]]
name = "saga-basic-saga"
path = "src/main.rs"

[dependencies]
nitinol-saga = { path = "../../../nitinol-saga" }
nitinol-eventsource = { path = "../../../nitinol-eventsource" }
nitinol-persistence = { path = "../../../nitinol-persistence" }
nitinol-runtime = { path = "../../../nitinol-runtime" }
async-trait = "0.1"
bytes = "1"
futures-core = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
